### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by TheAssassin** [redeclipse/promotional#1]
Third parties are supposed to use this, but at the moment there is no copyright declaration or explicit licensing.
We should add a proper license (I assume CC-By-SA is the way to go here, CC-By is too open) to resolve this issue.
Please beware that external, third party contents (even some screenshots or other images in the video, audio snippets or background music etc.) might be licensed differently, these licenses have to be added to the respective directories, too.

**Comment by IceflowRE** [comment]
Copyright goes to quin?
> transfer your rights to the Lead Developer for Red Eclipse, Quinton Reeves

But yes a explicit license for the files are missing

**Comment by TheAssassin** [comment]
Where did you find that quote?
Also, just for clarification, copyright would'nt go to anyone but the author in any case I could think of, but you may give up on several rights (like with CC-0) or you may transfer some of them to other people (like selling source code or stuff like that). That's the whole purpose of licensing: granting single permissions to third parties. These contracts explicitly define who may do what with the subject of the license.

**Comment by TheAssassin** [comment]
Ah, I see, it's in the README. I doubt that this is legally ok though, and might lead to problems in the future. Primarily, it is not clear what "rights" means and/or includes.
I also don't know if someone would want to give up copyright or ownership. This is actually not necessary at all, and leads to more problems than what it's worth.

At the moment, it is also not really possible for any third party to make use of the contents, as such a kind of homebrew license agreement would have to be checked by the legal department of potential users, which is usually too much work for them. I apprehend some organisations such as news sites or small blogs would rather not use the material just to make sure there won't be any legal problems.

The best approach with such a repository is adding a license that is acceptable to the owner (@qreeves in this case). Then, contributors would license their work under the exact same terms by uploading files. Everyone would still have the copyright of their own work, but as soon as the work is published under such a license, everyone would be free to share this work in the future under the license's terms. There cannot be any problems with that in the future, as soon as it has been published initially, this "contract" between users and authors will be valid for (almost) forever.

> This includes accepting that any royalties and/or revenue generated through our redistribution of the content belong the Lead Developer for Red Eclipse, Quinton Reeves, and will be used as he deems fit.

This is an understandable sentence, but similar rights must be granted to third parties, too. Otherwise contents might not even be used on websites with ads.

Thus, a license that would cover everything would be CC-By-SA (this is actually the most restrictive license that could be applied, NC would prohibit the above use case for example).
I would just begin to use that, everyone's happy, everyone's rights are protected, Red Eclipse can make use of the data as well as any third party, noone has to give up too many rights, perfect situation.

One more point to think about: If contributors would be forced to follow what has been written in the README, they would potentially not be allowed to reuse their own creations or modify them. That's not acceptable to many creative people, and probably not even legal to enforce. I would be careful about that.

**Comment by qreeves** [comment]
What's written in the README isn't a license, it is a redistribution agreement that grants me the ability to monetise things like YouTube videos, which in turn gets fed back in to the project. It's just you have to be very clear about this sort of thing, especially when dealing with YouTube.

The LICENSE for anything *that I create* is the Red Eclipse General License. This is and always will be CC-BY-SA. Contributors are free to license their own works differently, but must pick a license that is compatible with the project's philosophy of not restricting commercial use. In addition to this, contributors need to agree to my redistribution of the content they submit.

Give me a second while I copy over the license.

**Comment by TheAssassin** [comment]
Thanks for making things a little more clear.
As far as I can see it, your redistribution agreement enforces people to grant you a license that contains the points you require. That's fine indeed, and required for this repository to work as intended.
Though, I'd like to add a few more words on how to contribute properly, like "do you want to dual-license your work or can't you just license it with a license covering the points", e.g. by suggesting suitable licenses.
Also, I'd like to note that we should add something like "and the Red Eclipse team" so that others are able to reuse the work for advertising, too. Otherwise, you're pretty much preventing anyone but your person to do PR for the project. And I think you have a significant interest in us others doing PR, too.

**Comment by qreeves** [comment]
I already did that.
