### ISSUE TITLE
Twitch Box-Art

### ISSUE THREAD

**Issue by IceflowRE** [redeclipse/promotional#2]
As pointed out by `ZephaniahNoah` on Discord Red Eclipse does not have any box art available on Twitch.
1. The game must already exist in the Twitch game directory.
2. The image must be a .jpg file and must be under 1MB in file size.
3. The image size needs to be 600px x 800px.
4. The image cannot contain a developer logo, platform logo, website link, any sort of advertisement, or an ESRB rating. Please use official box art!
5. The image must include the title of the game. We will not accept an image that contains only a game logo.
6. The image must be high resolution. Pixelated images will not be approved unless this is part of the game branding or design.
7- Please review the Twitch Community Guidelines and Twitch Terms of Service. Any box art that violates these guidelines will not be approved.

https://help.twitch.tv/customer/en/portal/articles/2348988-adding-a-game-and-box-art-to-the-directory

Now two attempts from myself:
<section>
    <img width="50%" src="https://user-images.githubusercontent.com/10883690/51805971-4cb51f80-2274-11e9-94b8-0190e54bd52b.png">
    <img width="50%" src="https://user-images.githubusercontent.com/10883690/51805972-52126a00-2274-11e9-9df0-7594e2133bfa.png">
</section>
(*click for full resolution*)

@qreeves i guess you are the one who must register the art then.

**Comment by SniperGoth** [comment]
Maybe a silhouette of the player character could go along with it somewhere?

**Comment by qreeves** [comment]
Twitch now uses IGDB and details have been updated there.
