### ISSUE TITLE
Add colors used in Red Eclipse to this repository?

### ISSUE THREAD

**Issue by fkorax** [redeclipse/promotional#6]
I've struggled to find exact values for the colors used in-game (e.g. the team colors).
It would be useful if these color values (or links to them) were available in the promotional repository.

For example, the only place I could find exact values for the team colors was in [`src/game/player.h`](https://github.com/redeclipse/base/blob/6984ecb67ddbf8c4719d20517394bb44b9d2a238/src/game/player.h) in the [redeclipse/base](https://github.com/redeclipse/base) repository.

**Comment by IceflowRE** [comment]
You are right, the values are defined here: https://github.com/redeclipse/base/blob/6984ecb67ddbf8c4719d20517394bb44b9d2a238/src/game/player.h#L94

| | |
|-|-|
| Neutral | #707070 |
| Alpha | #1040F8 |
| Omega | #FF3210 |

**Comment by fkorax** [comment]
I would like to include those in the repository itself, maybe in a `colors/` subdirectory, along with the other colors used in the brand (e.g. the dark red used in the background for the main screen, promo material and website).

**Comment by qreeves** [comment]
@thomorl Please feel free to submit pull requests.

**Comment by fkorax** [comment]
Do the source files (SVG, GIMP, or other) for the logo / in-game background still exist?
I was unable to locate them in any of the repositories I've looked through.

**Comment by qreeves** [comment]
Most of that was before we started to obsessively keep source materials in a separate repository. The in-game background is actually captured from in-game as it is now a shader composite rather than a static image. The rest is lost to time, and one of the reasons I'm looking for someone to make new branding images.
